# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 08 Feb 2021 12:05:45 +0000
*	@ALL	0
einstellungen:%GROUP%:*	%GROUP%	1
einstellungen:allgemein:*	@ALL	1
navbar	@ALL	1
playground:*	@ALL	16
start	@ALL	1
user:%USER%	%USER%	1
user:%USER%:*	%USER%	16
wiki	@ALL	1
wiki:*	@ALL	1
