<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Mon, 18 Oct 2021 11:14:46 +0200
 */

$conf['title'] = 'schulwiki';
$conf['lang'] = 'de';
$conf['template'] = 'bootstrap3';
$conf['license'] = '0';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['typography'] = '0';
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['showuseras'] = 'username_link';
$conf['toptoclevel'] = '2';
$conf['tocminheads'] = '1';
$conf['maxtoclevel'] = '5';
$conf['maxseclevel'] = '0';
$conf['useheading'] = '1';
$conf['sneaky_index'] = 1;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['subscribers'] = 1;
$conf['subscribe_time'] = 60;
$conf['mailfrom'] = 'testlehrer@grg8.at';
$conf['updatecheck'] = 0;
$conf['plugin']['authldap']['attributes'] = array();
$conf['plugin']['catlist']['nocache'] = 1;
$conf['plugin']['catlist']['hide_acl_nsnotr'] = 1;
$conf['plugin']['catlist']['showhead'] = 0;
$conf['plugin']['icons']['defaultPack'] = 'mdi';
$conf['plugin']['move']['allowrename'] = '@admin';
$conf['plugin']['newpagetemplate']['prettytitles'] = 1;
$conf['plugin']['smtp']['smtp_host'] = 'smtp.gmail.com';
$conf['plugin']['smtp']['smtp_port'] = 587;
$conf['plugin']['smtp']['smtp_ssl'] = 'tls';
$conf['plugin']['smtp']['auth_user'] = 'testlehrer@grg8.at';
$conf['plugin']['smtp']['auth_pass'] = 'PA55W0RD';
$conf['tpl']['bootstrap3']['leftSidebarGrid'] = 'col-sm-2 col-md-2';
$conf['tpl']['bootstrap3']['rightSidebarGrid'] = 'col-sm-2 col-md-2';
$conf['tpl']['bootstrap3']['sidebarShowPageTitle'] = 0;
$conf['tpl']['bootstrap3']['showTools'] = 'logged';
$conf['tpl']['bootstrap3']['individualTools'] = 1;
$conf['tpl']['bootstrap3']['showIndividualTool'] = 'site';
$conf['tpl']['bootstrap3']['tableStyle'] = 'striped,bordered,hover,condensed';
$conf['tpl']['bootstrap3']['showWikiInfo'] = 0;
$conf['tpl']['bootstrap3']['tocCollapseSubSections'] = 0;
$conf['tpl']['bootstrap3']['tocCollapseOnScroll'] = 0;
$conf['tpl']['bootstrap3']['tocCollapsed'] = 1;
$conf['tpl']['bootstrap3']['discussionPage'] = 'kommentar:@ID@';
$conf['tpl']['bootstrap3']['browserTitle'] = '@TITLE@ ';
$conf['tpl']['bootstrap3']['browserTitleCharSepNS'] = '/';
$conf['tpl']['bootstrap3']['showPageIcons'] = 0;
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
