# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Mon, 08 Feb 2021 12:05:45 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$ARyn28m006eZrATM8YQhv.jdm9A6JqQ4l.yfVbsshlTmrjDvL4YqG:admin:123@456.789:admin
